# ===============LICENSE_START=======================================================
# Acumos Apache-2.0
# ===================================================================================
# Copyright (C) 2017-2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
# ===================================================================================
# This Acumos software file is distributed by AT&T and Tech Mahindra
# under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============LICENSE_END=========================================================
version: '2'

services:

  elasticsearch:
    image:  ${NEXUS3_RELEASE_REGISTRY_LF}/${ELASTICSEARCH_IMAGE}
    volumes:
      - acumos-esdata:/usr/share/elasticsearch/data
      - ./snapshot-backup:/backup
    ports:
    #Node client default listens at 9200, metricbeat and logstash index data into Elasticsearch using this port.
     - "${ACUMOS_ELK_ELASTICSEARCH_PORT}:9200"
    #Transport client default is 9300 this port is used for nodes communication. If this port is not open, your nodes will not be able to form a cluster.
     - "${ACUMOS_ELK_NODE_PORT}:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx${ACUMOS_ELK_ES_JAVA_HEAP_MAX_SIZE} -Xms${ACUMOS_ELK_ES_JAVA_HEAP_MIN_SIZE}"
    networks:
      - elk

  logstash:
    image:  ${NEXUS3_RELEASE_REGISTRY_LF}/${LOGSTASH_IMAGE}
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
    #Logstash default listens at 5000, Filebeat agentship log to this port.
      - "${ACUMOS_ELK_LOGSTASH_PORT}:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx${ACUMOS_ELK_LS_JAVA_HEAP_MAX_SIZE} -Xms${ACUMOS_ELK_LS_JAVA_HEAP_MIN_SIZE}"
      ACUMOS_ELK_JDBC_DRIVER_LIBRARY: "/usr/share/logstash/vendor/bundle/mariadb-java-client-2.1.0.jar"
      ACUMOS_ELK_JDBC_DRIVER_CLASS: "org.mariadb.jdbc.Driver"
      ACUMOS_ELK_JDBC_CONNECTION_STRING: "jdbc:mariadb://databaseurl:port/databasename"
      ACUMOS_ELK_JDBC_USERNAME: "username"
      ACUMOS_ELK_JDBC_PASSWORD: "password"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image:  ${NEXUS3_RELEASE_REGISTRY_LF}/${KIBANA_IMAGE}
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
    #Kiban is accessed on the web browser. Used for visualization of logs.
      - "${ACUMOS_ELK_KIBANA_PORT}:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  elk-client:
      image: ${NEXUS3_RELEASE_REGISTRY_LF}/${ELK_CLIENT}
      environment:
          SPRING_APPLICATION_JSON: '{
              "server" : { 
                   "port" : 9006
               },
               "elk" : {
                   "host" : {
                       "url":"${ACUMOS_ELK_ELASTICSEARCH_HOST}"
                   },
                   "elasticssearch" : {
                               "port":${ACUMOS_ELK_ELASTICSEARCH_PORT}
                           },
                   "cronschedule": {
                       "createsnapshot":{
                           "time":"${ELK_CLIENT_CRONSCHEDULE_CREATESNAPSHOT_TIME}"
                       }
                   }
               }
          }'
      ports:
          - ${ACUMOS_ELK_CLIENT_PORT}:9006
      volumes:
          - cognita-logs:/maven/logs
      logging:
          driver: json-file          

networks:
  elk:
    driver: bridge

volumes:
    acumos-esdata:
        external: true
    cognita-logs:
        external: true
        
